#!/usr/bin/env bash

echo "Configure php.ini"

PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-"On"}
PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL & ~E_DEPRECATED & ~E_STRICT"}
PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"256M"}

sed -i \
    -e "s/^display_errors = Off/display_errors = ${PHP_DISPLAY_ERRORS}/" \
    -e "s/^error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = ${PHP_ERROR_REPORTING}/" \
    -e "s/^memory_limit = 128M/memory_limit = ${PHP_MEMORY_LIMIT}/" \
    /etc/php/${PHP_VERSION}/fpm/php.ini